namespace CDLib
{
	interface IAudioCDTrack
	{
		String Name{ get; };
		Windows.Foundation.TimeSpan Duration{ get; };
		UInt32 TrackNumber{ get; };
	};

	interface IAudioCD
	{
		IVectorView<IAudioCDTrack> Tracks{ get; };
		String Name{ get; };
	};

	interface IAudioCDDrive
	{
		Windows.Foundation.IReference<Char> DriveLetter{ get; };

		IAudioCD InsertedMedia{ get; };
	};

	interface IAudioCDPlayer requires Windows.Foundation.IClosable
	{
		IVectorView<IAudioCDDrive> GetDrives();

		IAudioCDTrack PlayingTrack{ get; };
		void PlayTrack(IAudioCDTrack track);
		void Play();
		void Pause();
	};

	static runtimeclass AudioCDPlayer
	{
		static IAudioCDPlayer GetPlayer();
	};
}
